blog/config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'
  post 'sessions/create'
  delete 'sessions/destroy'

  resources :friendships
  resources :users
  resources :posts
  resources :comments 
  root 'home#index' 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

blog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

blog/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

blog/app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: "User"
end

blog/app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
end

blog/app/models/user.rb
class User < ApplicationRecord
	has_many :posts, dependent: :destroy
	has_many :comments, dependent: :destroy
	has_many :friendships
	has_many :friends, :through => :friendships
end

blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  def current_user
  	if session[:user_id]
  		User.find(session["user_id"])		
  	end
  end
end

blog/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
  end
  def new
    @current_user = current_user
    @post = Post.find(params[:id])
    @comment = Comment.new
  end
  def create
    @current_user = current_user
    @comment = Comment.new(params[:comment])
    if @comment.save
      redirect_to users_path
    else
      render 'new'
    end
  end
  def show
  end 
  def edit
    @current_user = current_user
    @comment = Comment.find(params[:id])
  end
  def update
    @current_user = current_user
    @comment = Comment.find(params[:id])
    if @comment.update_attributes(params[:comment])
      redirect_to users_path
    else
      render 'edit'
    end
  end
  def destroy
    @current_user = current_user
    @comment = Comment.find(params[:id])
    if @comment.destroy
      redirect_to root_path
    end
  end
end

blog/app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def new
  end
  def index
    @current_user = current_user
    @users = User.all 
    @friends = Friendship.where(user_id: @current_user.id)
  end 
  def create
  	@current_user = current_user
    @friend = User.where(id: params[:id]).last
    @friendship = Friendship.new(user_id: @current_user.id, friend_id: @friend.id)
    if @friendship.save 
      redirect_to users_path
    else
      render 'new'
    end
  end
  def destroy
    @current_user = current_user
    @friendship = Friendship.find(params[:id])
    if @friendship.destroy
      redirect_to users_path
    end
  end
end

blog/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@current_user = current_user
  	@posts = Post.last(30).reverse
  end
end
 

blog/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @current_user = current_user
    @friends = Friendship.where(user_id: @current_user.id)
    @posts = Post.all.reverse
    @users = User.all
  end
  def new 
    @current_user = current_user
    @post = Post.new
  end
  def create
    @current_user = current_user
    params[:post][:user_id] = @current_user.id
    @post = Post.new(params[:post])
    if @post.save
      redirect_to users_path
    else
      render 'new'
    end
  end
  def show
    @current_user = current_user
    @posts = Post.all
    @post = Post.find(params[:id])
    @comments = Comment.where(post_id: @post.id)  
  end
  def edit
    @current_user = current_user
    @post = Post.find(params[:id])
  end
  def update
    @current_user = current_user
    @post = Post.find(params[:id])
    if @post.update_attributes(params[:post])
      redirect_to users_path
    else
      render 'edit'
    end
  end
  def destroy
    @current_user = current_user
    @post = Post.find(params[:id])
    if @post.destroy
      redirect_to root_path
    end
  end
end

blog/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  	@user = User.new
  end
  def create
  	@user = User.where(email: params[:user][:email]).last
  	if @user && @user.password == params[:user][:password]
  		session[:user_id] = @user.id 
  		redirect_to users_path
  	else
  		redirect_to sessions_new_path
  	end
  end
  def destroy
  	session[:user_id] = nil
  	redirect_to root_path
  end
end

blog/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @current_user = current_user
    @posts = Post.where(user_id: @current_user.id ).reverse
  end 
  def new
    @user = User.new 
  end
  def create
    @user = User.new(params[:user])
    if @user.save
      session[:user_id] = @user.id  
      redirect_to users_path 
    else  
      render 'new'
    end 
  end
  def show
    @user = User.find(params[:id])
    @current_user = current_user
    @posts = Post.where(user_id: @user.id) 
  end
  def edit
    @current_user = current_user 
  end
  def update
    @current_user = current_user
    if @current_user.update_attributes(params[:user])
      redirect_to users_path
    else
      render 'edit'
    end
  end
  def destroy
    @current_user = current_user
    if @current_user.destroy
      session[:user_id] = nil
      redirect_to root_path
    end
  end
end

blog/app/helpers/application_helper.rb
module ApplicationHelper
end

blog/app/helpers/comments_helper.rb
module CommentsHelper
end

blog/app/helpers/friendships_helper.rb
module FriendshipsHelper
end

blog/app/helpers/home_helper.rb
module HomeHelper
end

blog/app/helpers/posts_helper.rb
module PostsHelper
end

blog/app/helpers/sessions_helper.rb
module SessionsHelper
end

blog/app/helpers/users_helper.rb
module UsersHelper
end

blog/app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

blog/app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

blog/app/views/comments/edit.html.erb
<h1>Edit Comment</h1>
<%= form_for @comment do |f|   %>
	<%= f.label :content %>
	<%= f.text_area :content, autofocus: true, :cols => 100, :rows => 10  %>
	<%= f.submit 'Upload' %>
<% end %>

blog/app/views/comments/index.html.erb
<h1>Comments#index</h1>
<p>Find me in app/views/comments/index.html.erb</p>

blog/app/views/comments/new.html.erb
<h1>New Comment</h1>
<%= form_for @comment do |f|   %>
	<%= f.hidden_field :user_id, value: @post.user_id %>
	<%= f.hidden_field :post_id, value: @post.id  %>
	<%= f.label :content %>
	<%= f.text_area :content, autofocus: true, :cols => 100, :rows => 10  %>
	<%= f.submit 'Upload' %>
<% end %>

blog/app/views/comments/show.html.erb
<h1>Comments#show</h1>
<p>Find me in app/views/comments/show.html.erb</p>

blog/app/views/comments/update.html.erb
<h1>Comments#update</h1>
<p>Find me in app/views/comments/update.html.erb</p>

blog/app/views/friendships/create.html.erb
<h1>Friendships#create</h1>
<p>Find me in app/views/friendships/create.html.erb</p>

blog/app/views/friendships/destroy.html.erb
<h1>Friendships#destroy</h1>
<p>Find me in app/views/friendships/destroy.html.erb</p>

blog/app/views/friendships/index.html.erb
<h1>Friends List </h1>	
<% @friends.each do |friend| %>
	<%= friend.friend.first_name %>
	<%= friend.friend.last_name %>
	<%= link_to 'Remove Friend', friendship_path(friend.id), method: :delete %>
	<br>
<% end %>

blog/app/views/friendships/new.html.erb
<h1>Friendships#new</h1>
<p>Find me in app/views/friendships/new.html.erb</p>

blog/app/views/home/index.html.erb
<h1>Home</h1>
<% if @posts %>
	<% @posts.each do |post|  %>
		<div>
		<hr>
		<% if @current_user %>
			<%= link_to post.user.first_name + " " + post.user.last_name, post.user%>
		<% else %>
			<button><%= link_to post.user.first_name + " " + post.user.last_name, sessions_new_path%></button>
		<% end %>
		<br>
		<%= post.content %>
		<br>
		<% if @current_user && @current_user.id == post.user_id  %>
			<button><%= link_to 'edit Post', edit_post_path(post.id) %></button>
		<% end %>
		<button><%= link_to 'Comments', post_path(id: post.id) %> </button>
	</div>
		<br>
		<hr>
	<% end %>
<% end %> 

blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.0/css/materialize.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <nav>
      <div class="nav-wrapper">
        <a href="#" class="brand-logo">My Site</a>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
        <% if @current_user %>
          <li><%= link_to 'Home', users_path %></li>
          <li><%= link_to 'All Posts', root_path %></li>
          <li><%= link_to 'Friends Posts', posts_path %></li>
          <li><%= link_to 'Friends List', friendships_path %></li>
          <li><%= link_to 'Log Out', sessions_destroy_path, method: :delete %></li>
        <% end %>
        <% if !@current_user %>
          <li><%= link_to 'Home', root_path %></li>
          <li><%= link_to 'New User', new_user_path %></li>
          <li><%= link_to 'Log In', sessions_new_path %></li>
        <% end %>
        </ul>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

blog/app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

blog/app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

blog/app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<%= form_for @post do |f|   %>
	<%= f.label :content %>
	<%= f.text_area :content, autofocus: true, :cols => 100, :rows => 10  %>
	<%= f.submit 'Change' %>
<% end %>

blog/app/views/posts/index.html.erb
<h1>Friends Posts</h1>
<% @posts.each do |post|    %>
	<% @friends.each do |friend| %>
		<%if post.user.id == friend.friend_id %>
			<button><%= link_to post.user.first_name + " " + post.user.last_name, post.user%> </button>
			<br>
			<%= post.content %>
			<%= post.created_at %>
			<button><%= link_to 'Comments', post_path(id: post.id) %> </button>
			<hr>
		<% end %>
	<% end %>
<% end %>

blog/app/views/posts/new.html.erb
<h1>new Post</h1>
<%= form_for @post do |f|   %>
	<%= f.label :content %>
	<%= f.text_area :content, autofocus: true, :cols => 100, :rows => 10  %>
	<%= f.submit 'Upload' %>
<% end %>

blog/app/views/posts/show.html.erb
<h1>Post Comments</h1>
<%= @post.user.first_name %>
<%= @post.user.last_name %>
<br>
<%= @post.content %>
<hr>
<% if @current_user %>
	<button><%= link_to 'Create Comment', new_comment_path(id: @post.id)  %></button>
	<hr>
<% end %>
<% @comments.each do |comment|  %>
	<hr>
	<%= comment.user.first_name %>
	<%= comment.user.last_name %>
	<br>
	<%= comment.content %>
	<br>
	<% if @current_user && @current_user.id == comment.user_id %>
		<button><%= link_to 'Edit Comment', edit_comment_path(comment.id) %></button>
	<% end %>	
	<hr>
<% end %>

blog/app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>

blog/app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

blog/app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

blog/app/views/users/edit.html.erb
<h1>Edit</h1>
<%= form_for @current_user do |f|   %>
	<%= f.label :first_name %>
	<%= f.text_field :first_name, autofocus: true  %>
	<%= f.label :last_name  %>
	<%= f.text_field :last_name  %>
	<%= f.label :email  %>
	<%= f.email_field :email %>
	<%= f.label :password %>
	<%= f.password_field :password %>
	<%= f.submit %>
<% end %>

blog/app/views/users/index.html.erb
 <h1><%= @current_user.first_name  %>
 <div>
	 <%= @current_user.last_name  %>
	 </h1>
	 <button><%= link_to 'edit', edit_user_path(@current_user) %></button>
	 <button><%= link_to 'Delete', user_path(@current_user.id), method: :delete %></button>
	 <button><%= link_to 'New Post', new_post_path %></button>
</div>
<hr>
<% @posts.each do |post|  %>
 	<hr>
	<%= post.content %>
	<br>
	<button><%= link_to 'edit Post', edit_post_path(post.id) %></button>
	<button><%= link_to 'Comments', post_path(id: post.id) %> </button>
	<hr>
<% end %>

blog/app/views/users/new.html.erb
<h1>New User</h1>
<%= form_for @user do |f|   %>
	<%= f.label :first_name %>
	<%= f.text_field :first_name, autofocus: true  %>
	<%= f.label :last_name  %>
	<%= f.text_field :last_name  %>
	<%= f.label :email  %>
	<%= f.email_field :email %>
	<%= f.label :password %>
	<%= f.password_field :password %>
	<%= f.submit %>
<% end %>
<button><%= link_to 'Existing User', sessions_new_path %></button>

blog/app/views/users/show.html.erb
<h1><%= @user.first_name %>
<%= @user.last_name %></h1>
<% if @user != @current_user && !@current_user.friends.ids.include?(@user.id) %>
	<button><%= link_to 'Add To Friends List', friendships_path(id: @user.id), method: :post %></button>
<% end %>
<% @posts.each do |post|  %>
	<hr>
	<%= post.content  %>
	<br>
	<button><%= link_to 'Comments', post_path(id: post.id) %> </button>
	<hr>
<% end %>
  

blog/app/views/users/update.html.erb
<h1>Update User</h1>
<p>Find me in app/views/users/update.html.erb</p>